services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      KEY: "lankoandeousmane"
      SECRET: "lankoandeousmane"
      ADMIN_EMAIL: "admin@kikandi.com"
      ADMIN_PASSWORD: "L@nk0usm@ne"
      PUBLIC_URL: "https://jobizybackend.kikandi.com"
      DB_CLIENT: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "L@nk0usm@ne"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions